---

- hosts: all
  become: true
  tasks: 

  - name: install updates
    tags: always
    dnf:
      update_only: yes
      update_cache: yes

  - name: install httpd package
    tags: httpd
    dnf:
      name: httpd
      state: latest
  - name: add php support for apache
    tags: php
    dnf:
      name: php
      state: latest

  - name: start and enable httpd
    service: 
      name: httpd
      state: started
      enabled: true

  - name: open port 80 for http
    firewalld:
      port: 80/tcp
      permanent: true
      state: enabled
      immediate: true

  - name: install mariadb package
    dnf:
      name: 
        - mariadb
        - mariadb-server
      state: latest

  - name: starting mariadb
    service:
      name: mariadb
      tags: mariadb
      state: started
      enabled: true
