---

- hosts: all
  become: true
  tasks: 

  - name: update repo index
    dnf:
      update_cache: yes

  - name: install httpd package
    dnf:
      name: httpd
      state: latest
  - name: add php support for apache
    dnf:
      name: php
      state: latest

  - name: start and enable httpd
    service: 
      name: httpd
      state: started
      enabled: true

  - name: open port 80 for http
    firewalld:
      port: 80/tcp
      permanent: true
      state: enabled
      immediate: true
